#!/usr/bin/env bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
export CDPATH=
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

test -r /etc/cause/cause.conf &&
  source /etc/cause/cause.conf
test -r ~/.cause.conf &&
  source ~/.cause.conf

export CAUSE=${CAUSE:=/opt/cause}
export CASUEINC=${CASUEINC:=${CAUSE}/cause.sh}

source "${CAUSEINC}"

showhelp() {
  log "${MYNAME} <name>"
  exit 2
}

test $# -lt 1 &&
  showhelp

while test "=${1:0:1}" = "=-"; do
  case "=$1" in
  =-x)
    CAUSEDEBUG=1
    shift
    ;;
  =-h|=--h*)
    showhelp
    ;;
  esac
done

test -n "${CAUSEDEBUG:-}" && set -x

require $1
