#!/usr/bin/env bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
export CDPATH=
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

declare -A CAUSEGITMAP

test -r /etc/cause/cause.conf &&
  source /etc/cause/cause.conf
test -r ~/.cause.conf &&
  source ~/.cause.conf

export CAUSE=${CAUSE:=/opt/cause}
export CAUSEINC=${CAUSEINC:=${CAUSE}/cause.sh}

test -r "${CAUSEINC}" || {
  echo "Missing ${CAUSEINC} file, please export installation directory in CAUSE environment variable"
  exit 1
}

source "${CAUSEINC}"

showhelp() {
  log "$0 <name>"
  exit 2
}

test $# -lt 1 &&
  showhelp

while test $# -ge 1; do
  test "=${1:0:1}" = "=-" || break
  case "=$1" in
  =-x)
    CAUSEDEBUG=1
    shift
    ;;
  =-v)
    CAUSEVERBOSE=$(( ${CAUSEVERBOSE}+1 ))
    shift
    ;;
  =-h|=--h*)
    showhelp
    ;;
  *)
    echo "Unknown switch $1"
    showhelp
  esac
done

test $# -ge 1 || {
  echo Missing module name
  showhelp
}

test "${CAUSEDEBUG:-0}" -gt 0 && set -x

require $1
