#!/usr/bin/env bash
#
# shellcheck disable=SC1090
# shellcheck disable=SC2128
# shellcheck disable=SC2317
#
## this prologue is common to all executables:
test -z "$(type -p)" || { echo bash required; exit 1; }
set -Eueo pipefail

export CDPATH=
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

RRCONF="${RRCONF:=$(dirname "$(readlink -e "${BASH_SOURCE}" )" )}"
RRCONFINC="${RRCONF}/lib.sh"

export RRCONF
export RRCONFINC

test -r "${RRCONFINC}" || {
  echo "Check if configuration or installation directory is present in \${RRCONF}."
  echo "I cannot read file ${RRCONFINC} file."
  exit 1
}

# include all functions and command line variable checks
source "${RRCONFINC}"

## end of prologue
_replay "$@"
