#!/usr/bin/env bash
## this prologue is common to all executables:
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u

export RRCONF=${RRCONF:=$(dirname $(readlink -e ${BASH_SOURCE}))}

test -r "${RRCONF}/lib.sh" || {
  echo "Check if configuration or installation directory is present in \$RRCONF."
  echo "I cannot read file ${RRCONF}/lib.sh file."
  exit 1
}

export RRCONFINC="${RRCONF}/lib.sh"

# include all functions and command line variable checks
source "${RRCONF}/lib.sh"

## end of prologue
_require "$@"
